### ISSUE TITLE
不支持webdav导入歌词吗？

### ISSUE THREAD

**Issue by kindle939393** [xhongc/music-tag-web#107]
一选歌词就
元数据嵌入歌曲失败：インタビュア>>>インタビュア:错误信息:[Errno 1] Operation not permitted
--
系统异常,请联系管理员处理

明明给了管理员了
···

```
日志
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "applications/task/views.py", line 181, in applications.task.views.TaskViewSets.update_id3
  File "applications/task/services/update_ids.py", line 44, in applications.task.services.update_ids.update_music_info
  File "applications/task/services/music_save.py", line 363, in applications.task.services.music_save.MusicSaver.save
  File "component/music_tag/file.py", line 374, in component.music_tag.file.AudioFile.save
  File "/usr/local/lib/python3.9/site-packages/mutagen/_util.py", line 156, in wrapper
    return func(self, h, *args, **kwargs)
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/mutagen/_util.py", line 284, in _openfile
    raise MutagenError(e)
PermissionError: [Errno 1] Operation not permitted
], 请求URL->[/api/update_id3/], 请求方法->[POST] 请求参数->[{}]
开始匹配：/app/media/4円 - アイロニ.mp3
捕获未处理异常,异常具体堆栈->[Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/mutagen/_util.py", line 185, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mutagen/id3/_tags.py", line 56, in __init__
    data = fileobj.read(10)
PermissionError: [Errno 1] Operation not permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/mutagen/_util.py", line 275, in _openfile
    yield FileThing(fileobj, filename, filename)
  File "/usr/local/lib/python3.9/site-packages/mutagen/_util.py", line 156, in wrapper
    return func(self, h, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mutagen/_file.py", line 132, in save
    return self.tags.save(filething, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mutagen/_util.py", line 185, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mutagen/_util.py", line 156, in wrapper
    return func(self, h, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mutagen/id3/_file.py", line 254, in save
    header = ID3Header(filething.fileobj)
  File "/usr/local/lib/python3.9/site-packages/mutagen/_util.py", line 189, in wrapper
    reraise(exc_dest, err, sys.exc_info()[2])
  File "/usr/local/lib/python3.9/site-packages/mutagen/_util.py", line 43, in reraise
    raise tp(value).with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/mutagen/_util.py", line 185, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mutagen/id3/_tags.py", line 56, in __init__
    data = fileobj.read(10)
mutagen.id3._util.error: [Errno 1] Operation not permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "applications/task/views.py", line 181, in applications.task.views.TaskViewSets.update_id3
  File "applications/task/services/update_ids.py", line 44, in applications.task.services.update_ids.update_music_info
  File "applications/task/services/music_save.py", line 363, in applications.task.services.music_save.MusicSaver.save
  File "component/music_tag/file.py", line 374, in component.music_tag.file.AudioFile.save
  File "/usr/local/lib/python3.9/site-packages/mutagen/_util.py", line 156, in wrapper
    return func(self, h, *args, **kwargs)
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/mutagen/_util.py", line 284, in _openfile
    raise MutagenError(e)
PermissionError: [Errno 1] Operation not permitted
], 请求URL->[/api/update_id3/], 请求方法->[POST] 请求参数->[{}]

```
···

**Comment by xhongc** [comment]
目前不支持 webdav
