### ISSUE TITLE
自建的docker为什么是V1版本的，DEMO是V2版本的

### ISSUE THREAD

**Issue by grouse108** [xhongc/music-tag-web#130]
拉取的已经是latest版本了，是V2还没有上线吗？

另外自建docker的“搜索歌词标签”功能无效，提示“暂无歌曲信息”，下面是ssh界面的提示，是哪里设置有问题吗？

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/site-packages/gevent/_socketcommon.py", line 247, in getaddrinfo
    addrlist = get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags)
  File "/usr/local/lib/python3.9/site-packages/gevent/resolver/thread.py", line 63, in getaddrinfo
    return self.pool.apply(_socket.getaddrinfo, args, kwargs)
  File "/usr/local/lib/python3.9/site-packages/gevent/pool.py", line 161, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src/gevent/event.py", line 329, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 359, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 347, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 327, in gevent._gevent_cevent.AsyncResult._raise_exception
  File "/usr/local/lib/python3.9/site-packages/gevent/_compat.py", line 65, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/gevent/threadpool.py", line 167, in __run_task
    thread_result.set(func(*args, **kwargs))
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7f7488806c70>: Failed to resolve 'm.music.migu.cn' ([Errno -3] Temporary failure in name resolution)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='m.music.migu.cn', port=443): Max retries exceeded with url: /migu/remoting/scr_search_tag?rows=10&type=2&keyword=%E5%82%BB%E5%AD%90%E6%89%8D%E6%82%B2%E4%BC%A4-%E6%9C%B4%E6%A0%91&pgc=1 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f7488806c70>: Failed to resolve 'm.music.migu.cn' ([Errno -3] Temporary failure in name resolution)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "applications/task/services/music_resource.py", line 49, in applications.task.services.music_resource.MusicResource.fetch_id3_by_title
  File "applications/task/services/music_resource.py", line 138, in applications.task.services.music_resource.MiGuMusicClient.fetch_id3_by_title
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='m.music.migu.cn', port=443): Max retries exceeded with url: /migu/remoting/scr_search_tag?rows=10&type=2&keyword=%E5%82%BB%E5%AD%90%E6%89%8D%E6%82%B2%E4%BC%A4-%E6%9C%B4%E6%A0%91&pgc=1 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f7488806c70>: Failed to resolve 'm.music.migu.cn' ([Errno -3] Temporary failure in name resolution)"))
音乐平台搜索失败 HTTPSConnectionPool(host='m.music.migu.cn', port=443): Max retries exceeded with url: /migu/remoting/scr_search_tag?rows=10&type=2&keyword=%E5%82%BB%E5%AD%90%E6%89%8D%E6%82%B2%E4%BC%A4-%E6%9C%B4%E6%A0%91&pgc=1 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f7488806c70>: Failed to resolve 'm.music.migu.cn' ([Errno -3] Temporary failure in name resolution)"))

另外“翻译歌词文本”功能也无效

**Comment by lvhuilong** [comment]
遇到同样的问题，拉取的latest版本是v1

**Comment by xhongc** [comment]
是的，现在还是 v1 版本，V2 是我未发布的版本

**Comment by hhz522** [comment]
可以给个v2
版本吗
