### ISSUE TITLE
mac  m1 运行报错

### ISSUE THREAD

**Issue by hxzhouh** [xhongc/music-tag-web#15]
捕获未处理异常,异常具体堆栈->[Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/applications/task/views.py", line 196, in batch_auto_update_id3
    batch_auto_tag_task(timestamp, source_list, select_mode)
  File "/app/applications/task/tasks.py", line 270, in batch_auto_tag_task
    is_match = match_song(resource, task.full_path, select_mode)
  File "/app/applications/task/utils.py", line 42, in match_song
    songs = MusicResource(resource).fetch_id3_by_title(title)
  File "/app/applications/task/services/music_resource.py", line 32, in fetch_id3_by_title
    return self.resource.fetch_id3_by_title(title)
  File "/app/applications/task/services/kugou.py", line 204, in fetch_id3_by_title
    signature = getSignature(p)
  File "/app/applications/task/services/kugou.py", line 187, in getSignature
    js_obj = execjs.compile(js_str)
  File "/usr/local/lib/python3.9/site-packages/execjs/__init__.py", line 61, in compile
    return get().compile(source, cwd)
  File "/usr/local/lib/python3.9/site-packages/execjs/_runtimes.py", line 21, in get
    return get_from_environment() or _find_available_runtime()
  File "/usr/local/lib/python3.9/site-packages/execjs/_runtimes.py", line 49, in _find_available_runtime
    raise exceptions.RuntimeUnavailableError("Could not find an available JavaScript runtime.")
execjs._exceptions.RuntimeUnavailableError: Could not find an available JavaScript runtime.

抱歉不知道您还需要什么信息，先贴上 docker 日志

**Comment by xhongc** [comment]
> 捕获未处理异常,异常具体堆栈->[Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response response = wrapped_callback(request, *callback_args, **callback_kwargs) File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view return view_func(*args, **kwargs) File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 103, in view return self.dispatch(request, *args, **kwargs) File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 45, in _wrapper return bound_method(*args, **kwargs) File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 142, in _wrapped_view response = view_func(request, *args, **kwargs) File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 483, in dispatch response = self.handle_exception(exc) File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 443, in handle_exception self.raise_uncaught_exception(exc) File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in dispatch response = handler(request, *args, **kwargs) File "/app/applications/task/views.py", line 196, in batch_auto_update_id3 batch_auto_tag_task(timestamp, source_list, select_mode) File "/app/applications/task/tasks.py", line 270, in batch_auto_tag_task is_match = match_song(resource, task.full_path, select_mode) File "/app/applications/task/utils.py", line 42, in match_song songs = MusicResource(resource).fetch_id3_by_title(title) File "/app/applications/task/services/music_resource.py", line 32, in fetch_id3_by_title return self.resource.fetch_id3_by_title(title) File "/app/applications/task/services/kugou.py", line 204, in fetch_id3_by_title signature = getSignature(p) File "/app/applications/task/services/kugou.py", line 187, in getSignature js_obj = execjs.compile(js_str) File "/usr/local/lib/python3.9/site-packages/execjs/**init**.py", line 61, in compile return get().compile(source, cwd) File "/usr/local/lib/python3.9/site-packages/execjs/_runtimes.py", line 21, in get return get_from_environment() or _find_available_runtime() File "/usr/local/lib/python3.9/site-packages/execjs/_runtimes.py", line 49, in _find_available_runtime raise exceptions.RuntimeUnavailableError("Could not find an available JavaScript runtime.") execjs._exceptions.RuntimeUnavailableError: Could not find an available JavaScript runtime.
> 
> 抱歉不知道您还需要什么信息，先贴上 docker 日志

是个bug，dockre镜像里确实nodejs的依赖，我已经修复了，可以用镜像版本1.0.5

**Comment by xhongc** [comment]
hi，我创建一个交流群（二维码在 readme页面），感兴趣可以加入。群里会谈论项目新进展，和玩nas的交流，你有需要增加的功能可也沟通交流，期待你的加入！

ps. 不想被打扰，不加群也没关系，issue提的问题我也会回答。
