### ISSUE TITLE
Permission denied: '/app/supervisord.log'

### ISSUE THREAD

**Issue by da1234cao** [xhongc/music-tag-web#208]
我存储音乐的目录，在普通用户的家目录里面。

为了避免docker启用后，修改音乐文件的权限，我在docker-compose中，指定了用户。

```shell
version: '3'

services:
  music-tag:
    user: "1001:1001"
    image: xhongc/music_tag_web:latest
    container_name: music-tag-web
    ports:
      - "8002:8002"
    volumes:
      - /home/da1234cao/Sync/music:/app/media
      - /home/da1234cao/software/music-tag-web/config:/app/data  
    restart: always
```

此时启动docker失败，失败信息如下：

```shell
docker-compose up
Starting music-tag-web ... done
Attaching to music-tag-web
music-tag-web | Traceback (most recent call last):
music-tag-web |   File "/usr/bin/supervisord", line 33, in <module>
music-tag-web |     sys.exit(load_entry_point('supervisor==4.2.2', 'console_scripts', 'supervisord')())
music-tag-web |   File "/usr/lib/python3/dist-packages/supervisor/supervisord.py", line 359, in main
music-tag-web |     go(options)
music-tag-web |   File "/usr/lib/python3/dist-packages/supervisor/supervisord.py", line 369, in go
music-tag-web |     d.main()
music-tag-web |   File "/usr/lib/python3/dist-packages/supervisor/supervisord.py", line 72, in main
music-tag-web |     self.options.make_logger()
music-tag-web |   File "/usr/lib/python3/dist-packages/supervisor/options.py", line 1494, in make_logger
music-tag-web |     loggers.handle_file(
music-tag-web |   File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 419, in handle_file
music-tag-web |     handler = RotatingFileHandler(filename, 'a', maxbytes, backups)
music-tag-web |   File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 213, in __init__
music-tag-web |     FileHandler.__init__(self, filename, mode)
music-tag-web |   File "/usr/lib/python3/dist-packages/supervisor/loggers.py", line 160, in __init__
music-tag-web |     self.stream = open(filename, mode)
music-tag-web | PermissionError: [Errno 13] Permission denied: '/app/supervisord.log'

```

**Comment by da1234cao** [comment]
似乎和这个issue重复了：https://github.com/xhongc/music-tag-web/issues/119

所以，关闭该issue
