### ISSUE TITLE
【BUG】刮削到歌词了，但是显示未找到歌词

### ISSUE THREAD

**Issue by ChenDY2233** [xhongc/music-tag-web#234]
版本：v20240802
方式：手动刮削修改

点击右侧的箭头写入tag时，自动填充了歌词，但是又提示未找到歌词

![Snipaste_2024-08-07_23-10-32](https://github.com/user-attachments/assets/ca7a5da4-8a50-4cf4-88e0-f6a49d091eda)

**Comment by xhongc** [comment]
偶尔发生的吗

**Comment by xhongc** [comment]
我并没有复现你所描述的问题

**Comment by ChenDY2233** [comment]
录屏了操作过程，基本都会触发 ：

https://tmp.link/f/66b39dd52e94a

**Comment by xhongc** [comment]
我还是没复现这个问题，F12 进入检测页面
<img width="1391" alt="image" src="https://github.com/user-attachments/assets/dc15ce0d-9eb7-4dbb-8d10-2a3091ed5e72">
查看这两接口是否报错误

**Comment by ChenDY2233** [comment]
![image](https://github.com/user-attachments/assets/11d61ca5-0f3e-42ce-91a7-b9044e1373c4)

**Comment by kbore** [comment]
+1 碰到了一样的报错.

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 440, in handle_exception
    response = exception_handler(exc, context)
  File "/app/component/drf/generics.py", line 62, in exception_handler
    raise exception_mapping[exc_class_name](";".join(message_list))
component.utils.exceptions.ParamValidationError
] status_code->[40000] & client_message->[lyc: 该字段不能为空。] & args->[()]
