### ISSUE TITLE
V2 Docker 启动一段时间后异常关闭

### ISSUE THREAD

**Issue by my-world-only-me** [xhongc/music-tag-web#244]
日志信息: 
['/usr/local/bin/gunicorn', '-w', '1', '-b', '0.0.0.0:8001', 'django_vue_cli.wsgi:application', '--timeout', '120', '--worker-class=gevent']

捕获未处理异常,异常具体堆栈->[Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/views/static.py", line 42, in serve

    raise Http404(_('“%(path)s” does not exist') % {'path': fullpath})

django.http.response.Http404: ”/app/static/dist/img/icons/favicon.svg"不存在

], 请求URL->[/static/dist/img/icons/favicon.svg], 请求方法->[GET] 请求参数->[{}]

**Comment by my-world-only-me** [comment]
```
Skipping creation of musictag user because PUID or PGID is set to 0.

【sqlite】

['manage.py', 'migrate']

Operations to perform:

  Apply all migrations: admin, auth, contenttypes, django_celery_beat, django_celery_results, music, script_mgmt, sessions, task, user

Running migrations:

  No migrations to apply.

[2024-09-13 03:19:51 +0800] [9] [INFO] Starting gunicorn 20.1.0

[2024-09-13 03:19:51 +0800] [9] [INFO] Listening at: http://0.0.0.0:8001 (9)

[2024-09-13 03:19:51 +0800] [9] [INFO] Using worker: gevent

[2024-09-13 03:19:51 +0800] [10] [INFO] Booting worker with pid: 10

【sqlite】

['/usr/local/bin/gunicorn', '-w', '1', '-b', '0.0.0.0:8001', 'django_vue_cli.wsgi:application', '--timeout', '120', '--worker-class=gevent']

捕获未处理异常,异常具体堆栈->[Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/views/static.py", line 42, in serve

    raise Http404(_('“%(path)s” does not exist') % {'path': fullpath})

django.http.response.Http404: ”/app/static/dist/img/icons/favicon.svg"不存在

], 请求URL->[/static/dist/img/icons/favicon.svg], 请求方法->[GET] 请求参数->[{}]

Skipping creation of musictag user because PUID or PGID is set to 0.

【sqlite】

['manage.py', 'migrate']

Operations to perform:

  Apply all migrations: admin, auth, contenttypes, django_celery_beat, django_celery_results, music, script_mgmt, sessions, task, user

Running migrations:

  No migrations to apply.

[2024-09-13 03:27:21 +0800] [9] [INFO] Starting gunicorn 20.1.0

[2024-09-13 03:27:21 +0800] [9] [INFO] Listening at: http://0.0.0.0:8001 (9)

[2024-09-13 03:27:21 +0800] [9] [INFO] Using worker: gevent

[2024-09-13 03:27:21 +0800] [10] [INFO] Booting worker with pid: 10

【sqlite】

['/usr/local/bin/gunicorn', '-w', '1', '-b', '0.0.0.0:8001', 'django_vue_cli.wsgi:application', '--timeout', '120', '--worker-class=gevent']

捕获未处理异常,异常具体堆栈->[Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/kombu/utils/functional.py", line 32, in __call__

    return self.__value__

AttributeError: 'ChannelPromise' object has no attribute '__value__'



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/kombu/transport/virtual/base.py", line 951, in create_channel

    return self._avail_channels.pop()

IndexError: pop from empty list



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 552, in connect

    sock = self._connect()

  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 609, in _connect

    raise err

  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 597, in _connect

    sock.connect(socket_address)

  File "/usr/local/lib/python3.9/site-packages/gevent/_socketcommon.py", line 590, in connect

    self._internal_connect(address)

  File "/usr/local/lib/python3.9/site-packages/gevent/_socketcommon.py", line 634, in _internal_connect

    raise _SocketError(err, strerror(err))

ConnectionRefusedError: [Errno 111] Connection refused



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/kombu/connection.py", line 472, in _reraise_as_library_errors

    yield

  File "/usr/local/lib/python3.9/site-packages/kombu/connection.py", line 459, in _ensure_connection

    return retry_over_time(

  File "/usr/local/lib/python3.9/site-packages/kombu/utils/functional.py", line 318, in retry_over_time

    return fun(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/kombu/connection.py", line 934, in _connection_factory

    self._connection = self._establish_connection()

  File "/usr/local/lib/python3.9/site-packages/kombu/connection.py", line 860, in _establish_connection

    conn = self.transport.establish_connection()

  File "/usr/local/lib/python3.9/site-packages/kombu/transport/virtual/base.py", line 975, in establish_connection

    self._avail_channels.append(self.create_channel(self))

  File "/usr/local/lib/python3.9/site-packages/kombu/transport/virtual/base.py", line 953, in create_channel

    channel = self.Channel(connection)

  File "/usr/local/lib/python3.9/site-packages/kombu/transport/redis.py", line 744, in __init__

    self.client.ping()

  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1351, in ping

    return self.execute_command('PING')

  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 875, in execute_command

    conn = self.connection or pool.get_connection(command_name, **options)

  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 1185, in get_connection

    connection.connect()

  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 557, in connect

    raise ConnectionError(self._error_message(e))

redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.



The above exception was the direct cause of the following exception:



Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view

    return view_func(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 114, in view

    return self.dispatch(request, *args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper

    return bound_method(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view

    response = view_func(request, *args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 505, in dispatch

    response = self.handle_exception(exc)

  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 465, in handle_exception

    self.raise_uncaught_exception(exc)

  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception

    raise exc

  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 502, in dispatch

    response = handler(request, *args, **kwargs)

  File "applications/task/views.py", line 550, in applications.task.views.TaskViewSets.check_file_duplicates

  File "/usr/local/lib/python3.9/site-packages/celery/app/task.py", line 444, in delay

    return self.apply_async(args, kwargs)

  File "/usr/local/lib/python3.9/site-packages/celery/app/task.py", line 599, in apply_async

    return app.send_task(

  File "/usr/local/lib/python3.9/site-packages/celery/app/base.py", line 880, in send_task

    amqp.send_task_message(P, name, message, **options)

  File "/usr/local/lib/python3.9/site-packages/celery/app/amqp.py", line 522, in send_task_message

    ret = producer.publish(

  File "/usr/local/lib/python3.9/site-packages/kombu/messaging.py", line 186, in publish

    return _publish(

  File "/usr/local/lib/python3.9/site-packages/kombu/connection.py", line 556, in _ensured

    return fun(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/kombu/messaging.py", line 195, in _publish

    channel = self.channel

  File "/usr/local/lib/python3.9/site-packages/kombu/messaging.py", line 218, in _get_channel

    channel = self._channel = channel()

  File "/usr/local/lib/python3.9/site-packages/kombu/utils/functional.py", line 34, in __call__

    value = self.__value__ = self.__contract__()

  File "/usr/local/lib/python3.9/site-packages/kombu/messaging.py", line 234, in <lambda>

    channel = ChannelPromise(lambda: connection.default_channel)

  File "/usr/local/lib/python3.9/site-packages/kombu/connection.py", line 953, in default_channel

    self._ensure_connection(**conn_opts)

  File "/usr/local/lib/python3.9/site-packages/kombu/connection.py", line 459, in _ensure_connection

    return retry_over_time(

  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__

    self.gen.throw(typ, value, traceback)

  File "/usr/local/lib/python3.9/site-packages/kombu/connection.py", line 476, in _reraise_as_library_errors

    raise ConnectionError(str(exc)) from exc

kombu.exceptions.OperationalError: Error 111 connecting to 127.0.0.1:6379. Connection refused.

], 请求URL->[/api/check_file_duplicates/], 请求方法->[POST] 请求参数->[{}]

捕获未处理异常,异常具体堆栈->[Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/kombu/utils/functional.py", line 32, in __call__

    return self.__value__

AttributeError: 'ChannelPromise' object has no attribute '__value__'



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/kombu/transport/virtual/base.py", line 951, in create_channel

    return self._avail_channels.pop()

IndexError: pop from empty list



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 552, in connect

    sock = self._connect()

  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 609, in _connect

    raise err

  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 597, in _connect

    sock.connect(socket_address)

  File "/usr/local/lib/python3.9/site-packages/gevent/_socketcommon.py", line 590, in connect

    self._internal_connect(address)

  File "/usr/local/lib/python3.9/site-packages/gevent/_socketcommon.py", line 634, in _internal_connect

    raise _SocketError(err, strerror(err))

ConnectionRefusedError: [Errno 111] Connection refused



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/kombu/connection.py", line 472, in _reraise_as_library_errors

    yield

  File "/usr/local/lib/python3.9/site-packages/kombu/connection.py", line 459, in _ensure_connection

    return retry_over_time(

  File "/usr/local/lib/python3.9/site-packages/kombu/utils/functional.py", line 318, in retry_over_time

    return fun(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/kombu/connection.py", line 934, in _connection_factory

    self._connection = self._establish_connection()

  File "/usr/local/lib/python3.9/site-packages/kombu/connection.py", line 860, in _establish_connection

    conn = self.transport.establish_connection()

  File "/usr/local/lib/python3.9/site-packages/kombu/transport/virtual/base.py", line 975, in establish_connection

    self._avail_channels.append(self.create_channel(self))

  File "/usr/local/lib/python3.9/site-packages/kombu/transport/virtual/base.py", line 953, in create_channel

    channel = self.Channel(connection)

  File "/usr/local/lib/python3.9/site-packages/kombu/transport/redis.py", line 744, in __init__

    self.client.ping()

  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1351, in ping

    return self.execute_command('PING')

  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 875, in execute_command

    conn = self.connection or pool.get_connection(command_name, **options)

  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 1185, in get_connection

    connection.connect()

  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 557, in connect

    raise ConnectionError(self._error_message(e))

redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.



The above exception was the direct cause of the following exception:



Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view

    return view_func(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 114, in view

    return self.dispatch(request, *args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper

    return bound_method(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view

    response = view_func(request, *args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 505, in dispatch

    response = self.handle_exception(exc)

  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 465, in handle_exception

    self.raise_uncaught_exception(exc)

  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception

    raise exc

  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 502, in dispatch

    response = handler(request, *args, **kwargs)

  File "applications/task/views.py", line 240, in applications.task.views.TaskViewSets.batch_auto_update_id3

  File "/usr/local/lib/python3.9/site-packages/celery/app/task.py", line 444, in delay

    return self.apply_async(args, kwargs)

  File "/usr/local/lib/python3.9/site-packages/celery/app/task.py", line 599, in apply_async

    return app.send_task(

  File "/usr/local/lib/python3.9/site-packages/celery/app/base.py", line 880, in send_task

    amqp.send_task_message(P, name, message, **options)

  File "/usr/local/lib/python3.9/site-packages/celery/app/amqp.py", line 522, in send_task_message

    ret = producer.publish(

  File "/usr/local/lib/python3.9/site-packages/kombu/messaging.py", line 186, in publish

    return _publish(

  File "/usr/local/lib/python3.9/site-packages/kombu/connection.py", line 556, in _ensured

    return fun(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/kombu/messaging.py", line 195, in _publish

    channel = self.channel

  File "/usr/local/lib/python3.9/site-packages/kombu/messaging.py", line 218, in _get_channel

    channel = self._channel = channel()

  File "/usr/local/lib/python3.9/site-packages/kombu/utils/functional.py", line 34, in __call__

    value = self.__value__ = self.__contract__()

  File "/usr/local/lib/python3.9/site-packages/kombu/messaging.py", line 234, in <lambda>

    channel = ChannelPromise(lambda: connection.default_channel)

  File "/usr/local/lib/python3.9/site-packages/kombu/connection.py", line 953, in default_channel

    self._ensure_connection(**conn_opts)

  File "/usr/local/lib/python3.9/site-packages/kombu/connection.py", line 459, in _ensure_connection

    return retry_over_time(

  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__

    self.gen.throw(typ, value, traceback)

  File "/usr/local/lib/python3.9/site-packages/kombu/connection.py", line 476, in _reraise_as_library_errors

    raise ConnectionError(str(exc)) from exc

kombu.exceptions.OperationalError: Error 111 connecting to 127.0.0.1:6379. Connection refused.

], 请求URL->[/api/batch_auto_update_id3/], 请求方法->[POST] 请求参数->[{}]

捕获未处理异常,异常具体堆栈->[Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/views/static.py", line 42, in serve

    raise Http404(_('“%(path)s” does not exist') % {'path': fullpath})

django.http.response.Http404: ”/app/static/dist/img/icons/favicon.svg"不存在

], 请求URL->[/static/dist/img/icons/favicon.svg], 请求方法->[GET] 请求参数->[{}]

捕获未处理异常,异常具体堆栈->[Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/views/static.py", line 42, in serve

    raise Http404(_('“%(path)s” does not exist') % {'path': fullpath})

django.http.response.Http404: ”/app/static/dist/img/icons/favicon.svg"不存在

], 请求URL->[/static/dist/img/icons/favicon.svg], 请求方法->[GET] 请求参数->[{}]

捕获未处理异常,异常具体堆栈->[Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/views/static.py", line 42, in serve

    raise Http404(_('“%(path)s” does not exist') % {'path': fullpath})

django.http.response.Http404: ”/app/static/dist/img/icons/favicon.svg"不存在

], 请求URL->[/static/dist/img/icons/favicon.svg], 请求方法->[GET] 请求参数->[{}]

捕获未处理异常,异常具体堆栈->[Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/views/static.py", line 42, in serve

    raise Http404(_('“%(path)s” does not exist') % {'path': fullpath})

django.http.response.Http404: ”/app/static/dist/manifest.js"不存在

], 请求URL->[/static/dist/manifest.js], 请求方法->[GET] 请求参数->[{}]

捕获未处理异常,异常具体堆栈->[Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/views/static.py", line 42, in serve

    raise Http404(_('“%(path)s” does not exist') % {'path': fullpath})

django.http.response.Http404: ”/app/static/dist/manifest.js"不存在

], 请求URL->[/static/dist/manifest.js], 请求方法->[GET] 请求参数->[{}]

捕获未处理异常,异常具体堆栈->[Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/views/static.py", line 42, in serve

    raise Http404(_('“%(path)s” does not exist') % {'path': fullpath})

django.http.response.Http404: ”/app/static/dist/manifest.js"不存在

], 请求URL->[/static/dist/manifest.js], 请求方法->[GET] 请求参数->[{}]

捕获未处理异常,异常具体堆栈->[Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/views/static.py", line 42, in serve

    raise Http404(_('“%(path)s” does not exist') % {'path': fullpath})

django.http.response.Http404: ”/app/static/dist/manifest.js"不存在

], 请求URL->[/static/dist/manifest.js], 请求方法->[GET] 请求参数->[{}]

捕获未处理异常,异常具体堆栈->[Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/views/static.py", line 42, in serve

    raise Http404(_('“%(path)s” does not exist') % {'path': fullpath})

django.http.response.Http404: ”/app/static/dist/manifest.js"不存在

], 请求URL->[/static/dist/manifest.js], 请求方法->[GET] 请求参数->[{}]

捕获未处理异常,异常具体堆栈->[Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/views/static.py", line 42, in serve

    raise Http404(_('“%(path)s” does not exist') % {'path': fullpath})

django.http.response.Http404: ”/app/static/dist/favicon-32x32.png"不存在

], 请求URL->[/static/dist/favicon-32x32.png], 请求方法->[GET] 请求参数->[{}]

捕获未处理异常,异常具体堆栈->[Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/views/static.py", line 42, in serve

    raise Http404(_('“%(path)s” does not exist') % {'path': fullpath})

django.http.response.Http404: ”/app/static/dist/img/icons/favicon.svg"不存在

], 请求URL->[/static/dist/img/icons/favicon.svg], 请求方法->[GET] 请求参数->[{}]

捕获未处理异常,异常具体堆栈->[Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/views/static.py", line 42, in serve

    raise Http404(_('“%(path)s” does not exist') % {'path': fullpath})

django.http.response.Http404: ”/app/static/dist/img/icons/favicon.svg"不存在

], 请求URL->[/static/dist/img/icons/favicon.svg], 请求方法->[GET] 请求参数->[{}]

捕获未处理异常,异常具体堆栈->[Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/views/static.py", line 42, in serve

    raise Http404(_('“%(path)s” does not exist') % {'path': fullpath})

django.http.response.Http404: ”/app/static/dist/img/icons/favicon.svg"不存在

], 请求URL->[/static/dist/img/icons/favicon.svg], 请求方法->[GET] 请求参数->[{}]

捕获未处理异常,异常具体堆栈->[Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/views/static.py", line 42, in serve

    raise Http404(_('“%(path)s” does not exist') % {'path': fullpath})

django.http.response.Http404: ”/app/static/dist/img/icons/favicon.svg"不存在

], 请求URL->[/static/dist/img/icons/favicon.svg], 请求方法->[GET] 请求参数->[{}]

捕获未处理异常,异常具体堆栈->[Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/views/static.py", line 42, in serve

    raise Http404(_('“%(path)s” does not exist') % {'path': fullpath})

django.http.response.Http404: ”/app/static/dist/img/icons/favicon.svg"不存在

], 请求URL->[/static/dist/img/icons/favicon.svg], 请求方法->[GET] 请求参数->[{}]

捕获未处理异常,异常具体堆栈->[Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/views/static.py", line 42, in serve

    raise Http404(_('“%(path)s” does not exist') % {'path': fullpath})

django.http.response.Http404: ”/app/static/dist/img/icons/favicon.svg"不存在

], 请求URL->[/static/dist/img/icons/favicon.svg], 请求方法->[GET] 请求参数->[{}]


```

**Comment by mysteryzzp** [comment]
我现在最新版还是有这个问题。
v20241121
