### ISSUE TITLE
音频数量错误

### ISSUE THREAD

**Issue by maicss** [xhongc/music-tag-web#254]
v1免费用户

1. 音乐数量不对，我有7000+歌曲，只显示了4999
2. 4999的歌曲打开后，页面卡的厉害，几乎无法使用。我看到v2付费用户上写了支持后台任务，所以这个算是付费功能是么？

附log：

<details><summary>Details</summary>
<p>

Skipping creation of musictag user because PUID or PGID is set to 0.
【sqlite】
['manage.py', 'migrate']
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, django_celery_beat, django_celery_results, music, script_mgmt, sessions, task, user
Running migrations:
  No migrations to apply.
[2024-09-29 15:37:17 +0000] [9] [INFO] Starting gunicorn 20.1.0
[2024-09-29 15:37:17 +0000] [9] [INFO] Listening at: http://0.0.0.0:8001 (9)
[2024-09-29 15:37:17 +0000] [9] [INFO] Using worker: gevent
[2024-09-29 15:37:17 +0000] [10] [INFO] Booting worker with pid: 10
【sqlite】
['/usr/local/bin/gunicorn', '-w', '1', '-b', '0.0.0.0:8001', 'django_vue_cli.wsgi:application', '--timeout', '120', '--worker-class=gevent']
捕获主动抛出异常, 具体异常堆栈->[Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 493, in dispatch
    self.initial(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 411, in initial
    self.check_permissions(request)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 333, in check_permissions
    self.permission_denied(
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 462, in handle_exception
    response = exception_handler(exc, context)
  File "/app/component/drf/generics.py", line 62, in exception_handler
    raise exception_mapping[exc_class_name](";".join(message_list))
component.utils.exceptions.NotAuthenticatedError
] status_code->[40101] & client_message->[身份认证信息未提供。] & args->[()] 
捕获主动抛出异常, 具体异常堆栈->[Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 493, in dispatch
    self.initial(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 411, in initial
    self.check_permissions(request)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 333, in check_permissions
    self.permission_denied(
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 462, in handle_exception
    response = exception_handler(exc, context)
  File "/app/component/drf/generics.py", line 62, in exception_handler
    raise exception_mapping[exc_class_name](";".join(message_list))
component.utils.exceptions.NotAuthenticatedError
] status_code->[40101] & client_message->[身份认证信息未提供。] & args->[()] 
捕获主动抛出异常, 具体异常堆栈->[Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 493, in dispatch
    self.initial(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 411, in initial
    self.check_permissions(request)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 333, in check_permissions
    self.permission_denied(
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 462, in handle_exception
    response = exception_handler(exc, context)
  File "/app/component/drf/generics.py", line 62, in exception_handler
    raise exception_mapping[exc_class_name](";".join(message_list))
component.utils.exceptions.NotAuthenticatedError
] status_code->[40101] & client_message->[身份认证信息未提供。] & args->[()] 
捕获未处理异常,异常具体堆栈->[Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/static.py", line 42, in serve
    raise Http404(_('“%(path)s” does not exist') % {'path': fullpath})
django.http.response.Http404: ”/app/static/dist/img/icons/favicon.svg"不存在
], 请求URL->[/static/dist/img/icons/favicon.svg], 请求方法->[GET] 请求参数->[{}]

</p>
</details>

**Comment by xhongc** [comment]
你的音频文件都是在一个目录下的吗，这样页面加载太多会卡，一个目录现在限制展示 5000 个文件。
v2 具有更多的功能 ，详细查看：https://xiers-organization.gitbook.io/music-tag-web-v2

**Comment by maicss** [comment]
所以这些都是设计如此，不是BUG是么？

**Comment by xhongc** [comment]
对， 不建议一个目录下太多音频。
