### ISSUE TITLE
【Bug问题】: worker 重启

### ISSUE THREAD

**Issue by WarlockFish** [xhongc/music-tag-web#312]
### docker镜像版本

2.3.1

### MusicTagWeb 版本

V2

### bug 描述

worker 服务总是重启
我是从2.1.9 升级到2.3.1版本 ，docker 版本

### 系统日志（可填）

```shell
supervisorctl status
beat                             RUNNING   pid 357, uptime 0:00:02
gunicorn                         RUNNING   pid 41, uptime 0:04:34
nginx                            RUNNING   pid 8, uptime 0:04:54
redis                            RUNNING   pid 9, uptime 0:04:54
worker                           STARTING
xiaoai                           RUNNING   pid 13, uptime 0:04:54
```

supervisord.log
```
2024-12-26 19:29:15,034 INFO success: beat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-12-26 19:29:15,035 INFO exited: worker (terminated by SIGKILL; not expected)
2024-12-26 19:29:15,037 INFO spawned: 'worker' with pid 444
2024-12-26 19:29:16,739 INFO success: worker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-12-26 19:29:16,740 INFO exited: beat (terminated by SIGKILL; not expected)
2024-12-26 19:29:16,763 INFO spawned: 'beat' with pid 446
2024-12-26 19:29:17,826 INFO success: beat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-12-26 19:29:17,882 INFO exited: worker (terminated by SIGKILL; not expected)
2024-12-26 19:29:18,663 INFO spawned: 'worker' with pid 449
2024-12-26 19:29:18,664 INFO reaped unknown pid 448 (terminated by SIGPIPE)
2024-12-26 19:29:19,941 INFO success: worker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-12-26 19:29:20,973 INFO exited: beat (terminated by SIGKILL; not expected)
2024-12-26 19:29:20,979 INFO spawned: 'beat' with pid 452
2024-12-26 19:29:21,942 INFO exited: worker (terminated by SIGKILL; not expected)
2024-12-26 19:29:22,543 INFO spawned: 'worker' with pid 454
2024-12-26 19:29:22,543 INFO success: beat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

celeryworker_err.log
```
/usr/local/lib/python3.9/site-packages/celery/platforms.py:833: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
/usr/local/lib/python3.9/site-packages/celery/platforms.py:833: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
/usr/local/lib/python3.9/site-packages/celery/platforms.py:833: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
```
```

**Comment by xhongc** [comment]
进容器里查看日志内容 /app/log 下

**Comment by WarlockFish** [comment]
需要看哪个日志

**Comment by WarlockFish** [comment]
> 进容器里查看日志内容 /app/log 下

需要看哪个日志

**Comment by xhongc** [comment]
worker 和 beat 的

**Comment by WarlockFish** [comment]
celeryworker.log
```
CORS_ORIGIN_WHITELIST: ['http://127.0.0.1:8080']
CSRF_TRUSTED_ORIGINS: ['http://*', 'https://*']
程序启动数据库：SQLite
程序启动方式：V2部署
['/usr/local/bin/celery', '-A', 'django_vue_cli.celery_app', 'worker', '-l', 'error', '-Ofair', '-P', 'gevent', '-Q', 'high_queue,celery']

 -------------- celery@e9a324781a00 v5.5.0b2 (immunity)
--- ***** -----
-- ******* ---- Linux-6.8.0-51-generic-x86_64-with-glibc2.31 2024-12-27 04:10:06
- *** --- * ---
- ** ---------- [config]
- ** ---------- .> app:         django_vue_cli:0x72a3677a92e0
- ** ---------- .> transport:   redis://127.0.0.1:6379/6
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 4 (gevent)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                .> high_queue       exchange=high_queue(direct) key=high_queue

CORS_ORIGIN_WHITELIST: ['http://127.0.0.1:8080']
CSRF_TRUSTED_ORIGINS: ['http://*', 'https://*']
程序启动数据库：SQLite
程序启动方式：V2部署
['/usr/local/bin/celery', '-A', 'django_vue_cli.celery_app', 'worker', '-l', 'error', '-Ofair', '-P', 'gevent', '-Q', 'high_queue,celery']
CORS_ORIGIN_WHITELIST: ['http://127.0.0.1:8080']
CSRF_TRUSTED_ORIGINS: ['http://*', 'https://*']
程序启动数据库：SQLite
程序启动方式：V2部署
['/usr/local/bin/celery', '-A', 'django_vue_cli.celery_app', 'worker', '-l', 'error', '-Ofair', '-P', 'gevent', '-Q', 'high_queue,celery']
CORS_ORIGIN_WHITELIST: ['http://127.0.0.1:8080']
CSRF_TRUSTED_ORIGINS: ['http://*', 'https://*']
程序启动数据库：SQLite
程序启动方式：V2部署
['/usr/local/bin/celery', '-A', 'django_vue_cli.celery_app', 'worker', '-l', 'error', '-Ofair', '-P', 'gevent', '-Q', 'high_queue,celery']
CORS_ORIGIN_WHITELIST: ['http://127.0.0.1:8080']
CSRF_TRUSTED_ORIGINS: ['http://*', 'https://*']
程序启动数据库：SQLite
程序启动方式：V2部署
['/usr/local/bin/celery', '-A', 'django_vue_cli.celery_app', 'worker', '-l', 'error', '-Ofair', '-P', 'gevent', '-Q', 'high_queue,celery']
CORS_ORIGIN_WHITELIST: ['http://127.0.0.1:8080']
CSRF_TRUSTED_ORIGINS: ['http://*', 'https://*']
程序启动数据库：SQLite
程序启动方式：V2部署
['/usr/local/bin/celery', '-A', 'django_vue_cli.celery_app', 'worker', '-l', 'error', '-Ofair', '-P', 'gevent', '-Q', 'high_queue,celery']
CORS_ORIGIN_WHITELIST: ['http://127.0.0.1:8080']
CSRF_TRUSTED_ORIGINS: ['http://*', 'https://*']
程序启动数据库：SQLite
程序启动方式：V2部署
CORS_ORIGIN_WHITELIST: ['http://127.0.0.1:8080']
CSRF_TRUSTED_ORIGINS: ['http://*', 'https://*']
程序启动数据库：SQLite
程序启动方式：V2部署
['/usr/local/bin/celery', '-A', 'django_vue_cli.celery_app', 'worker', '-l', 'error', '-Ofair', '-P', 'gevent', '-Q', 'high_queue,celery']
CORS_ORIGIN_WHITELIST: ['http://127.0.0.1:8080']
CSRF_TRUSTED_ORIGINS: ['http://*', 'https://*']
程序启动数据库：SQLite
程序启动方式：V2部署
['/usr/local/bin/celery', '-A', 'django_vue_cli.celery_app', 'worker', '-l', 'error', '-Ofair', '-P', 'gevent', '-Q', 'high_queue,celery']

 -------------- celery@e9a324781a00 v5.5.0b2 (immunity)
--- ***** -----
-- ******* ---- Linux-6.8.0-51-generic-x86_64-with-glibc2.31 2024-12-27 04:10:28
- *** --- * ---
- ** ---------- [config]
- ** ---------- .> app:         django_vue_cli:0x74c696f8e2e0
- ** ---------- .> transport:   redis://127.0.0.1:6379/6
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 4 (gevent)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                .> high_queue       exchange=high_queue(direct) key=high_queue

CORS_ORIGIN_WHITELIST: ['http://127.0.0.1:8080']
CSRF_TRUSTED_ORIGINS: ['http://*', 'https://*']
程序启动数据库：SQLite
程序启动方式：V2部署
['/usr/local/bin/celery', '-A', 'django_vue_cli.celery_app', 'worker', '-l', 'error', '-Ofair', '-P', 'gevent', '-Q', 'high_queue,celery']
```


celeryworker_err.log
```
User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
/usr/local/lib/python3.9/site-packages/celery/platforms.py:833: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
/usr/local/lib/python3.9/site-packages/celery/platforms.py:833: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
/usr/local/lib/python3.9/site-packages/celery/platforms.py:833: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
/usr/local/lib/python3.9/site-packages/celery/platforms.py:833: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
```

celerybeat.log
```
['/usr/local/bin/celery', '-A', 'django_vue_cli.celery_app', 'beat', '-l', 'ERROR']
__    -    ... __   -        _
LocalTime -> 2024-12-31 11:21:21
Configuration ->
    . broker -> redis://127.0.0.1:6379/6
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> django_celery_beat.schedulers.DatabaseScheduler

    . logfile -> [stderr]@%ERROR
    . maxinterval -> 5.00 seconds (5s)
CORS_ORIGIN_WHITELIST: ['http://127.0.0.1:8080']
CSRF_TRUSTED_ORIGINS: ['http://*', 'https://*']
程序启动数据库：SQLite
程序启动方式：V2部署
celery beat v5.5.0b2 (immunity) is starting.
['/usr/local/bin/celery', '-A', 'django_vue_cli.celery_app', 'beat', '-l', 'ERROR']
CORS_ORIGIN_WHITELIST: ['http://127.0.0.1:8080']
CSRF_TRUSTED_ORIGINS: ['http://*', 'https://*']
程序启动数据库：SQLite
程序启动方式：V2部署
celery beat v5.5.0b2 (immunity) is starting.
['/usr/local/bin/celery', '-A', 'django_vue_cli.celery_app', 'beat', '-l', 'ERROR']
```

celerybeat_err.log
```
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: locking protocol

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/apps/beat.py", line 113, in start_scheduler
    service.start()
  File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 634, in start
    humanize_seconds(self.scheduler.max_interval))
  File "/usr/local/lib/python3.9/site-packages/kombu/utils/objects.py", line 40, in __get__
    return super().__get__(instance, owner)
  File "/usr/local/lib/python3.9/functools.py", line 993, in __get__
    val = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 677, in scheduler
    return self.get_scheduler()
  File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 668, in get_scheduler
    return symbol_by_name(self.scheduler_cls, aliases=aliases)(
  File "/usr/local/lib/python3.9/site-packages/django_celery_beat/schedulers.py", line 231, in __init__
    Scheduler.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/beat.py", line 264, in __init__
    self.setup_schedule()
  File "/usr/local/lib/python3.9/site-packages/django_celery_beat/schedulers.py", line 239, in setup_schedule
    self.install_default_entries(self.schedule)
  File "/usr/local/lib/python3.9/site-packages/django_celery_beat/schedulers.py", line 361, in schedule
    self._schedule = self.all_as_schedule()
  File "/usr/local/lib/python3.9/site-packages/django_celery_beat/schedulers.py", line 245, in all_as_schedule
    for model in self.Model.objects.enabled():
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: locking protocol
```

**Comment by WarlockFish** [comment]
```
root@e9a324781a00:/app/data# ls -lh
total 201M
drwxr-xr-x 2 root root    6 Sep 15 18:51 bin
drwxr-xr-x 2 root root    6 Sep 15 18:51 log
-rw-r--r-- 1 root root 197M Dec 28 12:08 music_tag.db
-rw-r--r-- 1 root root  32K Dec 28 15:50 music_tag.db-shm
-rw-r--r-- 1 root root 4.0M Dec 28 15:49 music_tag.db-wal
drwxr-xr-x 2 root root    6 Sep 15 18:51 tmp
```

**Comment by jianxuanbing** [comment]
Beat 一直提示 
[2025-01-10 14:49:36,034: ERROR/MainProcess] beat: Connection error: [Errno 111] Connection refused. Trying again in 32.0 seconds...
[2025-01-10 14:50:09,338: ERROR/MainProcess] beat: Connection error: [Errno 111] Connection refused. Trying again in 32.0 seconds...
[2025-01-10 14:50:42,474: ERROR/MainProcess] beat: Connection error: [Errno 111] Connection refused. Trying again in 32.0 seconds...
[2025-01-10 14:51:15,477: ERROR/MainProcess] beat: Connection error: [Errno 111] Connection refused. Trying again in 32.0 seconds...
[2025-01-10 14:51:47,994: ERROR/MainProcess] beat: Connection error: [Errno 111] Connection refused. Trying again in 32.0 seconds...
[2025-01-10 14:52:20,758: ERROR/MainProcess] beat: Connection error: [Errno 111] Connection refused. Trying again in 32.0 seconds...
[2025-01-10 14:52:53,589: ERROR/MainProcess] beat: Connection error: [Errno 111] Connection refused. Trying again in 32.0 seconds...
[2025-01-10 14:53:26,073: ERROR/MainProcess] beat: Connection error: [Errno 111] Connection refused. Trying again in 32.0 seconds...
[2025-01-10 14:54:01,519: ERROR/MainProcess] beat: Connection error: [Errno 111] Connection refused. Trying again in 2.0 seconds...
[2025-01-10 14:54:03,629: ERROR/MainProcess] beat: Connection error: [Errno 111] Connection refused. Trying again in 4.0 seconds...
[2025-01-10 14:54:07,667: ERROR/MainProcess] beat: Connection error: [Errno 111] Connection refused. Trying again in 6.0 seconds...
[2025-01-10 14:54:13,749: ERROR/MainProcess] beat: Connection error: [Errno 111] Connection refused. Trying again in 8.0 seconds...
[2025-01-10 14:54:21,904: ERROR/MainProcess] beat: Connection error: [Errno 111] Connection refused. Trying again in 10.0 seconds...
[2025-01-10 14:54:32,249: ERROR/MainProcess] beat: Connection error: [Errno 111] Connection refused. Trying again in 12.0 seconds...
[2025-01-10 14:54:44,378: ERROR/MainProcess] beat: Connection error: [Errno 111] Connection refused. Trying again in 14.0 seconds...
[2025-01-10 14:54:58,672: ERROR/MainProcess] beat: Connection error: [Errno 111] Connection refused. Trying again in 16.0 seconds...
[2025-01-10 14:55:15,292: ERROR/MainProcess] beat: Connection error: [Errno 111] Connection refused. Trying again in 18.0 seconds...
[2025-01-10 14:55:33,495: ERROR/MainProcess] beat: Connection error: [Errno 111] Connection refused. Trying again in 20.0 seconds...

**Comment by jianxuanbing** [comment]
[2025-01-10 14:54:32,829: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 12.00 seconds... (6/100)

[2025-01-10 14:54:45,419: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 14.00 seconds... (7/100)

[2025-01-10 14:54:59,618: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 16.00 seconds... (8/100)

[2025-01-10 14:55:15,804: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 18.00 seconds... (9/100)

[2025-01-10 14:55:34,123: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 20.00 seconds... (10/100)

[2025-01-10 14:55:54,400: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 22.00 seconds... (11/100)
