### ISSUE TITLE
我这边启动失败提示Unable to connect the Internet

### ISSUE THREAD

**Issue by itodouble** [xhongc/music-tag-web#38]
2023-08-23 22:49:28 | stdout | self.server_region = GuestSeverRegion().get_server_region
-- | -- | --
2023-08-23 22:49:28 | stdout | File "/app/component/translators/server.py", line 328, in get_server_region
2023-08-23 22:49:28 | stdout | raise TranslatorError('Unable to connect the Internet.\n\n')
2023-08-23 22:49:28 | stdout | component.translators.server.TranslatorError: Unable to connect the Internet.
2023-08-23 22:49:28 | stdout |  
2023-08-23 22:49:28 | stdout |  
2023-08-23 22:49:28 | stdout | tss = TranslatorsServer()
2023-08-23 22:49:28 | stdout | File "/app/component/translators/server.py", line 5025, in __init__
2023-08-23 22:49:28 | stdout | File "/app/django_vue_cli/urls.py", line 5, in <module>
2023-08-23 22:49:28 | stdout | from applications.task.urls import router as task_router
2023-08-23 22:49:28 | stdout | File "/app/applications/task/urls.py", line 3, in <module>
2023-08-23 22:49:28 | stdout | from . import views
2023-08-23 22:49:28 | stdout | File "/app/applications/task/views.py", line 21, in <module>
2023-08-23 22:49:28 | stdout | from applications.utils.translation import translation_lyc_text
2023-08-23 22:49:28 | stdout | File "/app/applications/utils/translation.py", line 8, in <module>
2023-08-23 22:49:28 | stdout | from component import translators as ts
2023-08-23 22:49:28 | stdout | File "/app/component/translators/__init__.py", line 5, in <module>
2023-08-23 22:49:28 | stdout | from .server import translate_text, translate_html, translators_pool, get_languages, preaccelerate_and_speedtest
2023-08-23 22:49:28 | stdout | File "/app/component/translators/server.py", line 5310, in <module>
2023-08-23 22:49:28 | stdout | all_namespaces = _load_all_namespaces(resolver)
2023-08-23 22:49:28 | stdout | File "/usr/local/lib/python3.9/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
2023-08-23 22:49:28 | stdout | url_patterns = getattr(resolver, 'url_patterns', [])
2023-08-23 22:49:28 | stdout | File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 80, in __get__
2023-08-23 22:49:28 | stdout | res = instance.__dict__[self.name] = self.func(instance)
2023-08-23 22:49:28 | stdout | File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 584, in url_patterns
2023-08-23 22:49:28 | stdout | patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
2023-08-23 22:49:28 | stdout | File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 80, in __get__
2023-08-23 22:49:28 | stdout | res = instance.__dict__[self.name] = self.func(instance)
2023-08-23 22:49:28 | stdout | File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 577, in urlconf_module
2023-08-23 22:49:28 | stdout | return import_module(self.urlconf_name)
2023-08-23 22:49:28 | stdout | File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
2023-08-23 22:49:28 | stdout | return _bootstrap._gcd_import(name[level:], package, level)
2023-08-23 22:49:28 | stdout | File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2023-08-23 22:49:28 | stdout | File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2023-08-23 22:49:28 | stdout | File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
2023-08-23 22:49:28 | stdout | File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
2023-08-23 22:49:28 | stdout | File "<frozen importlib._bootstrap_external>", line 850, in exec_module
2023-08-23 22:49:28 | stdout | File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2023-08-23 22:49:28 | stdout | File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
2023-08-23 22:49:28 | stdout | utility.execute()
2023-08-23 22:49:28 | stdout | File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 375, in execute
2023-08-23 22:49:28 | stdout | self.fetch_command(subcommand).run_from_argv(self.argv)
2023-08-23 22:49:28 | stdout | File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 323, in run_from_argv
2023-08-23 22:49:28 | stdout | self.execute(*args, **cmd_options)
2023-08-23 22:49:28 | stdout | File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 361, in execute
2023-08-23 22:49:28 | stdout | self.check()
2023-08-23 22:49:28 | stdout | File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 387, in check
2023-08-23 22:49:28 | stdout | all_issues = self._run_checks(
2023-08-23 22:49:28 | stdout | File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 65, in _run_checks
2023-08-23 22:49:28 | stdout | issues.extend(super()._run_checks(**kwargs))
2023-08-23 22:49:28 | stdout | File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 377, in _run_checks
2023-08-23 22:49:28 | stdout | return checks.run_checks(**kwargs)
2023-08-23 22:49:28 | stdout | File "/usr/local/lib/python3.9/site-packages/django/core/checks/registry.py", line 72, in run_checks
2023-08-23 22:49:28 | stdout | new_errors = check(app_configs=app_configs)
2023-08-23 22:49:28 | stdout | File "/usr/local/lib/python3.9/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
2023-08-23 22:49:28 | stdout | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='geolocation.onetrust.com', port=443): Max retries exceeded with url: /cookieconsentpub/v1/geo/location (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f89bad7fb80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-08-23 22:49:28 | stdout |  
2023-08-23 22:49:28 | stdout | During handling of the above exception, another exception occurred:
2023-08-23 22:49:28 | stdout |  
2023-08-23 22:49:28 | stdout | Traceback (most recent call last):
2023-08-23 22:49:28 | stdout | File "/app/component/translators/server.py", line 317, in get_server_region
2023-08-23 22:49:28 | stdout | data = json.loads(requests.get(self.get_addr_url, headers=_headers_fn(self.get_addr_url)).text[9:-2])
2023-08-23 22:49:28 | stdout | File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 73, in get
2023-08-23 22:49:28 | stdout | return request("get", url, params=params, **kwargs)
2023-08-23 22:49:28 | stdout | File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 59, in request
2023-08-23 22:49:28 | stdout | return session.request(method=method, url=url, **kwargs)
2023-08-23 22:49:28 | stdout | File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
2023-08-23 22:49:28 | stdout | resp = self.send(prep, **send_kwargs)
2023-08-23 22:49:28 | stdout | File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
2023-08-23 22:49:28 | stdout | r = adapter.send(request, **kwargs)
2023-08-23 22:49:28 | stdout | File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
2023-08-23 22:49:28 | stdout | raise ConnectionError(e, request=request)
2023-08-23 22:49:28 | stdout | requests.exceptions.ConnectionError: HTTPSConnectionPool(host='geolocation.onetrust.com', port=443): Max retries exceeded with url: /cookieconsentpub/v1/geo/location (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f89bad7fb80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-08-23 22:49:28 | stdout |  
2023-08-23 22:49:28 | stdout | During handling of the above exception, another exception occurred:
2023-08-23 22:49:28 | stdout |  
2023-08-23 22:49:28 | stdout | Traceback (most recent call last):
2023-08-23 22:49:28 | stdout | File "/app/manage.py", line 22, in <module>
2023-08-23 22:49:28 | stdout | main()
2023-08-23 22:49:28 | stdout | File "/app/manage.py", line 18, in main
2023-08-23 22:49:28 | stdout | execute_from_command_line(sys.argv)
2023-08-23 22:49:28 | stdout | conn.connect()
2023-08-23 22:49:28 | stdout | File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 611, in connect
2023-08-23 22:49:28 | stdout | self.sock = sock = self._new_conn()
2023-08-23 22:49:28 | stdout | File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 218, in _new_conn
2023-08-23 22:49:28 | stdout | raise NewConnectionError(
2023-08-23 22:49:28 | stdout | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f89bad7fb80>: Failed to establish a new connection: [Errno 111] Connection refused
2023-08-23 22:49:28 | stdout |  
2023-08-23 22:49:28 | stdout | The above exception was the direct cause of the following exception:
2023-08-23 22:49:28 | stdout |  
2023-08-23 22:49:28 | stdout | Traceback (most recent call last):
2023-08-23 22:49:28 | stdout | File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
2023-08-23 22:49:28 | stdout | resp = conn.urlopen(
2023-08-23 22:49:28 | stdout | File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 844, in urlopen
2023-08-23 22:49:28 | stdout | retries = retries.increment(
2023-08-23 22:49:28 | stdout | File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 515, in increment
2023-08-23 22:49:28 | stdout | raise MaxRetryError(_pool, url, reason) from reason # type: ignore[arg-type]
2023-08-23 22:49:28 | stdout | Traceback (most recent call last):
2023-08-23 22:49:28 | stdout | File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 203, in _new_conn
2023-08-23 22:49:28 | stdout | sock = connection.create_connection(
2023-08-23 22:49:28 | stdout | File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
2023-08-23 22:49:28 | stdout | raise err
。。。

**Comment by itodouble** [comment]
大佬 能帮忙看下吗

**Comment by xhongc** [comment]
试试 镜像版本1.2.1

**Comment by itodouble** [comment]
可以了👍

**Comment by xhongc** [comment]
3q 4 u sponsor ，手机突然播报 社死现场

**Comment by xhongc** [comment]
是你吧 ！
