### ISSUE TITLE
关于docker部署之后报错

### ISSUE THREAD

**Issue by Higgbits** [xhongc/music-tag-web#4]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 166, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2002, "Can't connect to MySQL server on '127.0.0.1' (115)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/manage.py", line 22, in <module>
    main()
  File "/app/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 387, in check
    all_issues = self._run_checks(
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 64, in _run_checks
    issues = run_checks(tags=[Tags.database])
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.9/site-packages/django/core/checks/database.py", line 10, in check_database_backends
    issues.extend(conn.validation.check(**kwargs))
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/validation.py", line 9, in check
    issues.extend(self._check_sql_mode(**kwargs))
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/validation.py", line 13, in _check_sql_mode
    with self.connection.cursor() as cursor:
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 166, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2002, "Can't connect to MySQL server on '127.0.0.1' (115)")
``` 
应该是sql连接问题

**Comment by Higgbits** [comment]
Unraid

**Comment by Higgbits** [comment]
创建一个数据库 库名music 密码123456 后仍然报此错误

**Comment by xhongc** [comment]
> 

之前使用的是sqlite，后面我开发了subsonic api 之后使用的是mysql，是需要mysql 镜像的，我可以发一版 sqlite的版本吧

**Comment by Higgbits** [comment]
> > 
> 
> 之前使用的是sqlite，后面我开发了subsonic api 之后使用的是mysql，是需要mysql 镜像的，我可以发一版 sqlite的版本吧

感谢了，刚好有服务器刮削歌词的需求，不知什么时候可以解决？

**Comment by xhongc** [comment]
> > > 
> > 
> > 
> > 之前使用的是sqlite，后面我开发了subsonic api 之后使用的是mysql，是需要mysql 镜像的，我可以发一版 sqlite的版本吧
> 
> 感谢了，刚好有服务器刮削歌词的需求，不知什么时候可以解决？

docker pull registry.cn-hangzhou.aliyuncs.com/charles0519/music_tag_web:1.0.0

已经打包sqlite版本是1.0.0版本。it working。

**Comment by xhongc** [comment]
hi，我创建一个交流群（二维码在 readme页面），感兴趣可以加入。群里会谈论项目新进展，和玩nas的交流，你有需要增加的功能可也沟通交流，期待你的加入！

ps. 不想被打扰，不加群也没关系，issue提的问题我也会回答。
