### ISSUE TITLE
提示身份认证信息,请问这个需要理会吗?

### ISSUE THREAD

**Issue by 95121808** [xhongc/music-tag-web#83]
我用的unraid docker环境,目前唯一的报错就是"身份认证信息未提供",请问这个要怎么操作,需要提高docker的UID和GID等权限吗?
![image](https://github.com/xhongc/music-tag-web/assets/66406177/08999900-6370-44d8-827c-e31b33281eb4)
`"Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 440, in handle_exception
    response = exception_handler(exc, context)
  File "/app/component/drf/generics.py", line 62, in exception_handler
    raise exception_mapping[exc_class_name](";".join(message_list))
component.utils.exceptions.NotAuthenticatedError
] status_code->[40101] & client_message->[身份认证信息未提供。] & args->[()] "`

**Comment by xhongc** [comment]
什么操作时，能正常使用，就不用理会

**Comment by 95121808** [comment]
谢谢答复,请问DOCKER部署的,如果开启自动后可以关闭网页然后不用理会了吗?一切让他自己运行?&nbsp;


Docker-D
***@***.***







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月13日(星期一) 下午3:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xhongc/music-tag-web] 提示身份认证信息,请问这个需要理会吗? (Issue #83)





 
什么操作时，能正常使用，就不用理会

**Comment by xhongc** [comment]
目前还不行，还是同步阻塞的操作
